sylius_twig_hooks:
  hooks:
      'sylius_admin.priceeio_sync_plugin.index':
          sidebar:
            template: '@SyliusAdmin/shared/crud/common/sidebar.html.twig'
            priority: 200
          navbar:
            template: '@SyliusAdmin/shared/crud/common/navbar.html.twig'
            priority: 100
          content:
            template: '@SyliusAdmin/shared/crud/common/content.html.twig'
            priority: 0

      'sylius_admin.priceeio_sync_plugin.index.content':
        flashes:
          template: '@SyliusAdmin/shared/crud/common/content/flashes.html.twig'
          priority: 300
        header:
          template: '@SyliusAdmin/shared/crud/common/content/header.html.twig'
          priority: 200
        form:
            template: '@PriceeIOSyncPlugin/admin/sync/_form.html.twig'
            priority: 100

      'sylius_admin.priceeio_sync_plugin.index.content.header':
        title_block:
          template: '@SyliusAdmin/shared/crud/common/content/header/title_block.html.twig'
          priority: 0

      'sylius_admin.priceeio_sync_plugin.index.content.header.title_block':
        title:
          template: '@SyliusAdmin/shared/crud/common/content/header/title_block/title.html.twig'
          configuration:
            title: sylius.ui.admin.priceeio_sync_plugin.index.title
            sylius_test_html_attribute: 'dashboard-header'
          priority: 100
