# Delete these routes and define your own shop routes here

priceeio_sync_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: PriceeIO\SyncPlugin\Controller\GreetingController::staticallyGreetAction
        name: ~

priceeio_sync_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: PriceeIO\SyncPlugin\Controller\GreetingController::dynamicallyGreetAction
        name: ~
