# Delete these routes and define your own shop routes here

priceeio_sylius_example_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: PriceeIO\SyliusExamplePlugin\Controller\GreetingController::staticallyGreetAction
        name: ~

priceeio_sylius_example_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: PriceeIO\SyliusExamplePlugin\Controller\GreetingController::dynamicallyGreetAction
        name: ~
